MomentumPlus.Relay.Web/Controllers/MediaController.cs
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using System;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class MediaController : BaseController
    {
        //IOC
        public MediaController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        public ActionResult GetFile(Guid Id)
        {
            if (Id == Guid.Empty)
                return HttpNotFound();

            FileViewModel file = Services.MediaService.GetFile(Id);

            if (file == null)
                return HttpNotFound();

            return File(file.BinaryData, file.ContentType);
        }
        [AllowAnonymous]
        public ActionResult GetImage(Guid imageId, int? width = null, int? height = null)
        {
            if (imageId == Guid.Empty)
                return HttpNotFound();

            FileViewModel img = Services.MediaService.GetImage(imageId, width, height);

            if (img == null)
                return HttpNotFound();

            return File(img.BinaryData, img.ContentType);
        }

        public ActionResult GetAvatarForEmployee(Guid employeeId, int? width, int? height)
        {
            if(employeeId != Guid.Empty)
            {
                FileViewModel file = Services.MediaService.GetEmployeeAvatarImage(employeeId, width, height);

                if (file == null)
                    return HttpNotFound();

                return File(file.BinaryData, file.ContentType);
            }

            return HttpNotFound();
        }

        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult GetMyAvatar(int? width, int? height)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());

            FileViewModel file = Services.MediaService.GetEmployeeAvatarImage(userId, width, height);

            if (file == null)
                return HttpNotFound();

            return File(file.BinaryData, file.ContentType);
        }

        public ActionResult GetProjectAvatar(Guid projectId, int? width, int? height)
        {
            if (projectId != Guid.Empty)
            {
                FileViewModel file = Services.MediaService.GetProjectAvatarImage(projectId, width, height);

                if (file == null)
                    return HttpNotFound();

                return File(file.BinaryData, file.ContentType);
            }

            return HttpNotFound();
        }

    }
}

MomentumPlus.Relay.Web/Controllers/Reports/GlobalReportsController.cs
using System;
using System.Web.Mvc;
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using MvcPaging;
using Microsoft.AspNet.Identity;
using Rotativa;
using Rotativa.Options;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class GlobalReportsController : BaseController
    {
        //IOC
        public GlobalReportsController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        #region Common Global report methods

        public ActionResult Index()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            if (Services.AccessService.IsGlobalReportHistoryAndReceivedDisable(userId))
            {
                return RedirectToAction("TeamReport");
            }

            return RedirectToAction("HistoryReport");
        }


        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult HistoryReport(int? page, int? pageSize)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            IPagedList<HistoryGlobalReportItemViewModel> model = Services.GlobalReportService.GetHistoryReportsItemsForUser(userId, page, pageSize);
            return View("~/Views/Reports/GlobalReports/HistoryReport/Index.cshtml", model);
        }

        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult ReceivedReport(int? page, int? pageSize)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            IPagedList<ReceivedGlobalReportItemViewModel> model = Services.GlobalReportService.GetReceivedReportsItemsForUser(userId, page, pageSize);
            return View("~/Views/Reports/GlobalReports/ReceivedReport/Index.cshtml", model);
        }

        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult SharedReport(int? page, int? pageSize)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            IPagedList<SharedGlobalReportItemViewModel> model = Services.GlobalReportService.GetSharedReportsItemsForUser(userId, page, pageSize);
            return View("~/Views/Reports/GlobalReports/SharedReport/Index.cshtml", model);
        }

        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult TeamReport(int? page, int? pageSize, Guid? filterUserId, RotationType? filterRotationType)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            GlobalReportsListViewModel model = Services.GlobalReportService.GetTeamReportsItemsForUser(userId, filterUserId, filterRotationType, page, pageSize);
            return View("~/Views/Reports/GlobalReports/TeamReport/Index.cshtml", model);
        }

        #endregion


        #region QME Report

        [Route("/Reports/QMEReport")]
        [HttpGet]
        [AllowAnonymous]
        public ActionResult ReportPrint(Guid sourceId, bool isShift, bool isReceived = false, Guid? selectedSourceId = null)
        {
            string footerUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/GlobalReports/PdfFooter";

            string footerHtml = String.Format(" --footer-html {0} " +
                                              "--enable-local-file-access" +
                                              " --enable-javascript" +
                                              " --footer-spacing 1 " +
                                              " --encoding utf-8", footerUrl);

            var model = Services.ReportService.PopulateQMERotationReportViewModel(sourceId, isReceived ? ModuleSourceType.Received : ModuleSourceType.Draft, isShift, selectedSourceId);

            var pdfResult = new ViewAsPdf("~/Views/Reports/QMEReport/PrintQMEReport.cshtml", model)
            {
                FileName = "Rotation-Report.pdf",
                PageOrientation = Orientation.Portrait,
                MinimumFontSize = 18,
                IsGrayScale = false,
                IsJavaScriptDisabled = false,
                CustomSwitches = footerHtml,
                PageMargins = new Margins(10, 10, 10, 10)
            };

            var binary = pdfResult.BuildFile(ControllerContext);

            return File(binary, "application/pdf");
        }

        public ActionResult Report(Guid sourceId, bool isShift, bool isReceived = false, Guid? selectedSourceId = null)
        {
            var model = Services.ReportService.PopulateQMERotationReportViewModel(sourceId, isReceived ? ModuleSourceType.Received : ModuleSourceType.Draft, isShift, selectedSourceId);

            return View("~/Views/Reports/QMEReport/PrintQMEReport.cshtml", model);
        }

        [AllowAnonymous]
        public ActionResult PdfFooter(FooterViewModel model)
        {
            return PartialView("~/Views/Rotation/TaskBoard/PDFReport/_PrintFooter.cshtml", model);
        }

        #endregion

        #region Handover Report

        [Route("/Reports/HandoverReport")]
        [HttpGet]
        [AllowAnonymous]
        public ActionResult HandoverReport(Guid sourceId, bool isShift = false, bool isReceived = false, Guid? selectedSourceId = null)
        {
            string footerUrl = Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/GlobalReports/PdfFooter";

            string footerHtml = String.Format(" --footer-html {0} " +
                                              "--enable-local-file-access" +
                                              " --enable-javascript" +
                                              " --footer-spacing 1 " +
                                              " --encoding utf-8", footerUrl);

            var model = Services.ReportService.PopulateHandoverReportViewModel(sourceId, isReceived ? ModuleSourceType.Received : ModuleSourceType.Draft, isShift, selectedSourceId);

            var pdfResult = new ViewAsPdf("~/Views/Reports/HandoverReport/PrintHandoverReport.cshtml", model)
            {
                FileName = "Rotation-Report.pdf",
                PageOrientation = Orientation.Portrait,
                MinimumFontSize = 16,
                IsGrayScale = false,
                IsJavaScriptDisabled = false,
                CustomSwitches = footerHtml,
                PageMargins = new Margins(10, 10, 10, 10)
            };

            var binary = pdfResult.BuildFile(ControllerContext);

            return File(binary, "application/pdf");
        }


        public ActionResult Test(Guid sourceId, bool isShift, bool isReceived = false, Guid? selectedSourceId = null)
        {
            var model = Services.ReportService.PopulateHandoverReportViewModel(sourceId, isReceived ? ModuleSourceType.Received : ModuleSourceType.Draft, isShift, selectedSourceId);

            return View("~/Views/Reports/HandoverReport/PrintHandoverReport.cshtml", model);
        }

        #endregion
    }
}

MomentumPlus.Relay.Web/Views/Reports/GlobalReports/HistoryReport/Index.cshtml
@model IPagedList<HistoryGlobalReportItemViewModel>

@{
    Layout = "~/Views/Reports/GlobalReports/_Layout.cshtml";
}

<div class="page-content">
    <div class="global-report-table">
        <table class="table">
            <thead>
                <tr class="table-header">
                    <td class="date-title">Date</td>
                    <td class="received-from-title">Handover to</td>
                    <td class="position-title">Position</td>
                    <td class="rotation-type-title">Rotation</td>
                    <td class="items-title"># Items</td>
                    <td class="tasks-title"># Tasks</td>
                    <td class="action-icon-title"></td>
                </tr>
            </thead>
            <tbody class="table-content">
                <tr class="spacer-row"></tr>
                @if (Model.Any())
                {
                    foreach (var item in Model)
                    {
                        <tr class="report-row">
                            <td class="date-body">@item.DateString</td>
                            <td class="received-from-body">
                                <img src="@Url.Action("GetAvatarForEmployee", "Media", new { employeeId = item.HandoverToId })" />
                                <div class="user-name">@item.HandoverToName</div>
                            </td>
                            <td class="position-body">@item.PositionName</td>
                            <td class="rotation-type-body">@item.RotationType</td>
                            <td class="items-body">
                                <div class="circle">
                                    <div class="count">@item.ItemsNumber</div>
                                </div>
                            </td>
                            <td class="tasks-body">
                                <div class="circle">
                                    <div class="count">@item.TasksNumber</div>
                                </div>
                            </td>
                            <td class="action-icon-body @(item.IsQME ? "qme-action" : "")">
                                <a class="go-to-report" href="@Url.Action("Draft", "ReportBuilder", new { reportId = item.SourceId, reportType = item.RotationType })"></a>
                                <div class="pdf-report" source-Id="@item.SourceId" source-type="@item.RotationType"></div>
                                @if (item.IsQME)
                                {
                                    <div class="qme-pdf-report" source-Id="@item.SourceId" source-type="@item.RotationType"></div>
                                }
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr class="report-row">
                        <td colspan="7" class="text-center">
                            <strong>No reports to display.</strong>
                        </td>
                    </tr>
                }

                <tr class="spacer-row"></tr>
            </tbody>

        </table>
    </div>
    @if (Model.TotalItemCount > 5)
    {
        <div class="footer-block">
            <div class="view-block">
                <div class="eyes"></div>
                <div class="count-block">
                    <a href="@Url.Action("HistoryReport", "GlobalReports", new { pageSize = 5 })"><div class="counter @(Model.PageSize == 5 ? "active" : "" )">5</div></a>
                    <a href="@Url.Action("HistoryReport", "GlobalReports", new { pageSize = 10 })"><div class="counter @(Model.PageSize == 10 ? "active" : "" )">10</div></a>
                    <a href="@Url.Action("HistoryReport", "GlobalReports", new { pageSize = 15 })"><div class="counter @(Model.PageSize == 15 ? "active" : "" )">15</div></a>
                    <a href="@Url.Action("HistoryReport", "GlobalReports", new { pageSize = (Model.TotalItemCount != 0 ?  Model.TotalItemCount : 5) })"><div class="counter @(Model.PageSize == Model.TotalItemCount && Model.TotalItemCount != 5 && Model.TotalItemCount != 10 && Model.TotalItemCount != 15 ? "active" : "" )">All</div></a>
                </div>
            </div>
            <div class="pagination-block">
                <div class="pagination-pages">
                    @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount).Options(o => o
                            .DisplayTemplate("BootstrapPagination")
                            .MaxNrOfPages(1)
                            .DisplayFirstAndLastPage())
                </div>
            </div>
        </div>
    }
</div>