MomentumPlus.Relay.Web/Controllers/RotationManager/EmployeesController.cs
using MomentumPlus.Relay.Constants;
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using MvcPaging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MomentumPlus.Core.Authorization;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class EmployeesController : BaseController
    {
        //IOC
        public EmployeesController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        [HttpGet]
        public ActionResult Index()
        {
            return View("~/Views/RotationManager/Employees/Index.cshtml");
        }

        [HttpPost]
        public ActionResult GetEmployeesForTeam(int? page, Guid? teamId)
        {
            if (teamId.HasValue)
            {
                int currentPageIndex = page.HasValue ? page.Value - 1 : 0;
                var employees = Services.UserService
                                    .GetEmployeesForTeam(teamId.Value)
                                    .ToPagedList(currentPageIndex, NumericConstants.Paginator.PaginatorPageSize);

                return Json(new
                {
                    Employees = employees.Select(m => new { Id = m.Id, Name = m.Name + " " + m.Surname }).OrderBy( em => em.Name),
                    IsFirstPage = employees.IsFirstPage,
                    IsLastPage = employees.IsLastPage,
                    PageNumber = employees.PageNumber,
                    PageCount = employees.PageCount
                });
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult GetEmployeesForPosition(Guid positionId)
        {
            IEnumerable<EmployeeViewModel> employees = Services.UserService.GetEmployeesForPosition(positionId);

            return Json(employees.Select(m => new { Id = m.Id, Name = m.Name + " " + m.Surname }).OrderBy(em => em.Name));
        }

        [HttpPost]
        public ActionResult GetAllEmployees(Guid positionId, Guid? rotationOwnerId)
        {
            IEnumerable<EmployeeViewModel> employeesList = Services.UserService.GetAllEmployees();

            var employees = rotationOwnerId.HasValue
                ? employeesList.Where(e => e.Id != rotationOwnerId).OrderBy(e => e.Name)
                : employeesList.OrderBy(e => e.Name);
            return Json(employees.Select(m => new { Id = m.Id, Name = m.Name + " " + m.Surname }));
        }

        #region Create Dialog

        [HttpGet]
        public ActionResult CreateEmployeeDialog(CreateEmployeeViewModel model)
        {
            ModelState.Clear();
            model = (CreateEmployeeViewModel)Services.UserService.PopulateEmployeeModel(model);

            return PartialView("~/Views/RotationManager/Employees/_CreateEmployeeFormDialog.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEmployeeDialog(CreateEmployeeViewModel model, HttpPostedFileBase profileImage)
        {
            if(ModelState.IsValid)
            {
                if(!Services.UserService.IsEmployeeExist(model.Email))
                {
                    if(profileImage != null)
                    {
                        model.ImageId = Services.MediaService.AddImage("avatar", profileImage);
                    }
                    Services.UserService.AddEmployee(model);
                    return Content("ok");
                }
                else
                {
                    ModelState.AddModelError("Email", "User with the same login, already exist.");
                }
            }

            model = (CreateEmployeeViewModel)Services.UserService.PopulateEmployeeModel(model);
            return PartialView("~/Views/RotationManager/Employees/_CreateEmployeeFormDialog.cshtml", model);
        }

        #endregion

        #region Edit Dialog

        [HttpGet]
        public ActionResult EditEmployeeDialog(Guid EmployeeId)
        {
            if(EmployeeId != Guid.Empty)
            {
                EmployeeViewModel model = Services.UserService.GetEmployeeById(EmployeeId);
                TempData["OldAvatarId"] = model.ImageId;
                return PartialView("~/Views/RotationManager/Employees/_EditEmployeeFormDialog.cshtml", model);
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditEmployeeDialog(EmployeeViewModel model, HttpPostedFileBase profileImage)
        {
            if (ModelState.IsValid)
            {
                if (model.Id.HasValue && !Services.UserService.IsEmployeeExist(model.Email, model.Id.Value))
                {
                    if (profileImage != null)
                    {
                        model.ImageId = Services.MediaService.AddImage("avatar", profileImage);
                    }

                    if (Services.UserService.UpdateEmployee(model))
                    {
                        Guid? oldAvatarId = (Guid?)TempData["OldAvatarId"];
                        if (profileImage != null && oldAvatarId.HasValue)
                        {
                            Services.MediaService.RemoveImage(oldAvatarId.Value);
                        }

                        return Content("ok");
                    }
                    else if (model.ImageId.HasValue)
                    {
                        Services.MediaService.RemoveImage(model.ImageId.Value);
                    }
                }
                else
                {
                    ModelState.AddModelError("Email", "Employee with the same login already exist.");
                }

            }

            model = Services.UserService.PopulateEmployeeModel(model);
            return PartialView("~/Views/RotationManager/Employees/_EditEmployeeFormDialog.cshtml", model);
        }

        #endregion


        [HttpGet]
        [Authorize(Roles = iHandoverRoles.Relay.Administrator + "," + iHandoverRoles.Relay.iHandoverAdmin + "," + iHandoverRoles.Relay.ExecutiveUser)]
        public ActionResult ChangeEmployeePasswordDialog(Guid employee)
        {
            var model = new ChangeEmployeePasswordViewModel
            {
                EmployeeId = employee
            };

            return PartialView("~/Views/RotationManager/Employees/_ChangeEmployeePasswordFormDialog.cshtml", model);
        }

        [HttpPost]
        [Authorize(Roles = iHandoverRoles.Relay.Administrator + "," + iHandoverRoles.Relay.iHandoverAdmin + "," + iHandoverRoles.Relay.ExecutiveUser)]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeEmployeePasswordDialog(ChangeEmployeePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Services.UserService.ResetEmployeePassword(model.EmployeeId, model.NewPassword);
                    return Content("ok");
                }
                catch (Exception)
                {
                    return HttpNotFound();
                }
            }
            return PartialView("~/Views/RotationManager/Employees/_ChangeEmployeePasswordFormDialog.cshtml", model);
        }


    }
}

MomentumPlus.Relay.Web/Controllers/RotationManager/PositionsController.cs
using MomentumPlus.Relay.Constants;
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using MvcPaging;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class PositionsController : BaseController
    {
        //IOC
        public PositionsController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        [HttpPost]
        public ActionResult GetPositionsForSite(int? page, Guid siteId)
        {
            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;
            var positions = Services.PositionService.GetPositionsForSite(siteId)
                                .ToPagedList(currentPageIndex, NumericConstants.Paginator.PaginatorPageSize);
            return Json(new
            {
                Positions = positions.Select(m => new { Id = m.Id, Name = m.Name }),
                IsFirstPage = positions.IsFirstPage,
                IsLastPage = positions.IsLastPage,
                PageNumber = positions.PageNumber,
                PageCount = positions.PageCount
            });
        }

        [HttpPost]
        public ActionResult GetPositionForEmployee(Guid employeeId)
        {
            return Json(Services.PositionService.GetPositionForEmployee(employeeId));
        }

        #region Create Dialog

        [HttpGet]
        public ActionResult CreatePositionDialog(PositionViewModel model)
        {
            ModelState.Clear();

            model = Services.PositionService.PopulatePositionModel(model);
            ViewBag.Title = "Create Position";

            return PartialView("~/Views/RotationManager/Positions/_PositionFormDialog.cshtml", model);
        }

        [HttpPost]
        [ActionName("CreatePositionDialog")]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePositionDialog_post(PositionViewModel model)
        {

            if (ModelState.IsValid)
            {
                if (Services.PositionService.AddPosition(model))
                {
                    return Content("ok");
                }
                else
                {
                    ModelState.AddModelError("Name", "Position with the same Name, already exist.");
                }
            }

            model = Services.PositionService.PopulatePositionModel(model);


            return PartialView("~/Views/RotationManager/Positions/_PositionFormDialog.cshtml", model);
        }

        #endregion

        #region Edit Dialog

        [HttpGet]
        public ActionResult EditPositionDialog(Guid PositionId)
        {
            if (PositionId != Guid.Empty)
            {
                PositionViewModel model = Services.PositionService.GetPosition(PositionId);
                ViewBag.Title = "Edit Position";
                if (model != null)
                {
                    return PartialView("~/Views/RotationManager/Positions/_PositionFormDialog.cshtml", model);
                }
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPositionDialog(PositionViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (Services.PositionService.UpdatePosition(model))
                {
                    return Content("ok");
                }

                return HttpNotFound();
            }

            model = Services.PositionService.PopulatePositionModel(model);

            return PartialView("~/Views/RotationManager/Positions/_PositionFormDialog.cshtml", model);
        }

        #endregion
    }
}

MomentumPlus.Relay.Web/Controllers/RotationManager/RotationsController.cs
using MomentumPlus.Relay.Constants;
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using MvcPaging;
using System;
using System.Linq;
using System.Web.Mvc;
using MomentumPlus.Core.Authorization;
using MomentumPlus.Relay.Web.Helpers;

namespace MomentumPlus.Relay.Web.Controllers
{
    [Authorize(Roles = iHandoverRoles.Relay.Administrator + "," + iHandoverRoles.Relay.iHandoverAdmin + "," + iHandoverRoles.Relay.ExecutiveUser)]
    public class RotationsController : BaseController
    {
        //IOC
        public RotationsController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        // GET: Rotations
        public ActionResult Index()
        {
            AppSession.Current.ExitRotationViewModeUrl = Request.RawUrl;

            return View("~/Views/RotationManager/Rotations/Index.cshtml");
        }

        [HttpPost]
        public ActionResult GetRotationsForPosition(int? page, Guid positionId)
        {

            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;
            var rotations = Services.RotationService.GetRotationsForPosition(positionId)
                                .ToPagedList(currentPageIndex, NumericConstants.Paginator.PaginatorPageSize);
            return Json(new
            {
                Rotations = rotations.Select(m => new { Id = m.Id, Name = m.RotationOwner, userId = m.RotationOwnerId }),
                IsFirstPage = rotations.IsFirstPage,
                IsLastPage = rotations.IsLastPage,
                PageNumber = rotations.PageNumber,
                PageCount = rotations.PageCount
            });
        }

        #region Create Dialog

        [HttpGet]
        public ActionResult CreateRotationDialog(Guid? SiteId, Guid? PositionId)
        {
            ModelState.Clear();

            var model = Services.RotationService.PopulateEditRotationModel(new CreateRotationViewModel()
            {
                PositionId = PositionId,
                SiteId = SiteId
            });

            return PartialView("~/Views/RotationManager/Rotations/_CreateRotationFormDialog.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRotationDialog(CreateRotationViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (Services.RotationService.CreateFirstRotation(model))
                {
                    return Content("ok");
                }
                else
                {
                    ModelState.AddModelError("RotationOwnerId", "This employee already have rotation.");
                }
            }

            model = Services.RotationService.PopulateEditRotationModel(model);

            return PartialView("~/Views/RotationManager/Rotations/_CreateRotationFormDialog.cshtml", model);
        }

        #endregion

        #region Edit Dialog


        [HttpGet]
        public ActionResult EditRotationDialog(Guid RotationId)
        {
            if (RotationId != Guid.Empty)
            {
                EditRotationViewModel model = Services.RotationService.GetRotation(RotationId);
                if (model != null)
                {

                    model.CanChangeLineManager = User.IsInRole(iHandoverRoles.Relay.iHandoverAdmin) ||
                                                 User.IsInRole(iHandoverRoles.Relay.Administrator) ||
                                                 User.IsInRole(iHandoverRoles.Relay.ExecutiveUser) ||
                                                 User.IsInRole(iHandoverRoles.Relay.HeadLineManager);

                    return PartialView("~/Views/RotationManager/Rotations/_EditRotationFormDialog.cshtml", model);
                }
            }

            return HttpNotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRotationDialog(EditRotationViewModel model)
        {
            if (ModelState.IsValid)
            {
                if(Services.RotationService.UpdateRotation(model))
                {
                    return Content("ok");
                }

                return HttpNotFound();
            }

            model = Services.RotationService.PopulateEditRotationModel(model);

            return PartialView("~/Views/RotationManager/Rotations/_EditRotationFormDialog.cshtml", model);
        }

        #endregion
    }
}

MomentumPlus.Relay.Web/Views/RotationManager/Employees/Index.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Main/Authorized_Layout.cshtml";
}



@section Styles
{
    <style>
        .panel-heading a strong {
            font-size: 20px;
        }
    </style>
}


<div ng-app="EmployeesApp">
    <employees-app></employees-app>
</div>



@section Scripts
{
    <script src="~/Content/lib/angular/angular.js"></script>
    <script src="~/Content/js/relay/rotation-manager/modules/employees-app/employees-app.module.js"></script>
    <script src="~/Content/js/relay/rotation-manager/modules/employees-app/components/employees-panel/employees-panel.component.js"></script>
    <script src="~/Content/js/relay/rotation-manager/modules/employees-app/components/teams-panel/teams-panel.component.js"></script>
}

MomentumPlus.Relay.Web/Views/RotationManager/Employees/_ChangeEmployeePasswordFormDialog.cshtml
@model ChangeEmployeePasswordViewModel

<div Id="changeEmployeePasswordFormDialog" tabindex="-1" role="dialog" aria-labelledby="modalTitle" data-keyboard="false" data-backdrop="static" aria-hidden="true" class="modal fade">
    @using (Html.BeginForm("ChangeEmployeePasswordDialog", "Employees", FormMethod.Post, new { role = "form" }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.EmployeeId)

        <div class="modal-dialog  modal-sm">
            <div class="theme">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="row vertical-center">
                            <div class="col col-lg-8 col-md-8 col-sm-8 col-xs-8">
                                <div Id="modalTitle" class="modal-title">Change Password</div>
                            </div>
                            <div class="col col-lg-4 col-md-4 col-sm-4 col-xs-4 text-right">
                                <button type="submit" class="btn btn-save">Change</button>
                                <button type="button" data-dismiss="modal" aria-hidden="true" class="btn btn-close"></button>
                            </div>
                        </div>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">
                                <div class="field-container">
                                    <span class="title-select">@Html.LabelFor(model => model.NewPassword)</span>
                                    @Html.PasswordFor(model => model.NewPassword, new { @class = "simple-input", @placeholder = "Enter New Password" })
                                    @Html.ValidationMessageFor(model => model.NewPassword)
                                </div>
                            </div>
                            <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                <div class="field-container">
                                    <span class="title-select">@Html.LabelFor(model => model.ConfirmNewPassword)</span>
                                    @Html.PasswordFor(model => model.ConfirmNewPassword, new { @class = "simple-input", @placeholder = "Confirm New Password" })
                                    @Html.ValidationMessageFor(model => model.ConfirmNewPassword)
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    }
</div>

MomentumPlus.Relay.Web/Views/RotationManager/Employees/_CreateEmployeeFormDialog.cshtml
@model CreateEmployeeViewModel

<div Id="createEmployeeFormDialog" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true" class="modal fade employee-dialog">
    @using (Html.BeginForm("CreateEmployeeDialog", "Employees", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Id)

        <div class="modal-dialog">
            <div class="theme">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="row vertical-center">
                            <div class="col col-lg-9 col-md-9 col-sm-9 col-xs-9">
                                <div Id="modalTitle" class="modal-title">Create Employee</div>
                            </div>
                            <div class="col col-lg-3 col-md-3 col-sm-3 col-xs-3 text-right">
                                <button type="submit" class="btn btn-save">Save</button>
                                <button type="button" data-dismiss="modal" aria-hidden="true" class="btn btn-close"></button>
                            </div>
                        </div>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-2 text-center no-padding">
                                <div class="upload-photo">
                                    <div data-provides="fileinput" class="fileinput fileinput-new">
                                        <div data-trigger="fileinput" class="fileinput-preview thumbnail"></div>
                                        <div style="display: none">
                                            <span class="btn btn-default btn-file">
                                                <input Id="@Html.IdFor(model => model.ImageId)" name="ProfileImage" type="file" accept="image/*" />
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div style="cursor: pointer;" onclick="javascript: $('#ImageId').click();">
                                    <span class="btn btn-choose-image"></span>
                                    <span class="choose-image-title">edit photo</span>
                                </div>
                            </div>
                            <div class="col col-lg-4 col-md-4 col-sm-4 col-xs-4 col-xs-offset-1">
                                <div class="row">
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">
                                        <div class="field-container">
                                            <span class="title-select">@Html.LabelFor(model => model.Name)</span>
                                            @Html.TextBoxFor(model => model.Name, new {@class = "simple-input", @placeholder = "Enter Name"})
                                            @Html.ValidationMessageFor(model => model.Name)
                                        </div>
                                    </div>
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                        <div class="field-container">
                                            <span class="title-select">@Html.LabelFor(model => model.Surname)</span>
                                            @Html.TextBoxFor(model => model.Surname, new {@class = "simple-input", @placeholder = "Enter Surname"})
                                            @Html.ValidationMessageFor(model => model.Surname)
                                        </div>
                                    </div>
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                        <div class="field-container">
                                            <span class="title-select">@Html.LabelFor(m => m.Email)</span>
                                            @Html.TextBoxFor(m => m.Email, new {@class = "simple-input", @placeholder = "Enter Email"})
                                            @Html.ValidationMessageFor(m => m.Email)
                                        </div>
                                    </div>
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                        <div class="field-container">
                                            <span class="title-select">@Html.LabelFor(m => m.Password)</span>
                                            @Html.PasswordFor(m => m.Password, new {@class = "simple-input", @placeholder = "Enter Password"})
                                            @Html.ValidationMessageFor(m => m.Password)
                                        </div>
                                    </div>
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                        <div class="field-container">
                                            <span class="title-select">@Html.LabelFor(m => m.PasswordConfirm)</span>
                                            @Html.PasswordFor(m => m.PasswordConfirm, new {@class = "simple-input", @placeholder = "Confirm Password"})
                                            @Html.ValidationMessageFor(m => m.PasswordConfirm)
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col col-lg-4 col-md-4 col-sm-4 col-xs-4 col-xs-offset-1 fix-col">
                                <div class="row">
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">
                                        <div class="select-type">
                                            <span class="title-select">@Html.LabelFor(m => m.CompanyId)</span>
                                            @Html.DropDownListFor(m => m.CompanyId, Model.Companies, "Select Company", new { @class = "select-list" })
                                            @Html.ValidationMessageFor(m => m.CompanyId)
                                        </div>
                                    </div>
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                        <div class="select-type">
                                            <span class="title-select">@Html.LabelFor(m => m.PositionId)</span>
                                            @Html.DropDownListFor(m => m.PositionId, Model.Positions, "Select Position", new { @class = "select-list" })
                                            @Html.ValidationMessageFor(m => m.PositionId)
                                        </div>
                                    </div>
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                        <div class="select-type">
                                            <span class="title-select">@Html.LabelFor(m => m.TeamId)</span>
                                            @Html.DropDownListFor(m => m.TeamId, Model.Teams, "Select Team", new { @class = "select-list" })
                                            @Html.ValidationMessageFor(m => m.TeamId)
                                        </div>
                                    </div>

                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                        <div class="select-type">
                                            <span class="title-select">@Html.LabelFor(m => m.RotationPatternId)</span>
                                            @Html.DropDownListFor(m => m.RotationPatternId, Model.RotationPatterns, "Select Rotation Pattern", new { @class = "select-list" })
                                            @Html.ValidationMessageFor(m => m.RotationPatternId)
                                        </div>
                                    </div>

                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding margin-top-20">
                                        <div class="select-type">
                                            <span class="title-select">@Html.LabelFor(m => m.UserTypeId)</span>
                                            @Html.DropDownListFor(m => m.UserTypeId, Model.UserTypes, "Select User Type", new { @class = "select-list" })
                                            @Html.ValidationMessageFor(m => m.UserTypeId)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>